//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub hash: i64,
    #[sea_orm(nullable)]
    pub dir: u32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub bundle: u32,
    pub offset: u32,
    pub size: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bundles::Entity",
        from = "Column::Bundle",
        to = "super::bundles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bundles,
    #[sea_orm(
        belongs_to = "super::dirs::Entity",
        from = "Column::Dir",
        to = "super::dirs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dirs,
}

impl Related<super::bundles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bundles.def()
    }
}

impl Related<super::dirs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dirs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
