name: build

on:
  push:
    branches:
      - dev
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --release
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: autocommit
      - run: tree -H '.' --noreport --charset utf-8 -o index.html
        working-directory: output
      - uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'workflow_dispatch' || steps.autocommit.outputs.changes_detected == 'true'
        with:
          path: output
    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || needs.build.outputs.changes_detected == 'true'
    steps:
      - name: deploy gh-pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
